### ISSUE TITLE
Spurious dialog box when `transmission-turtle-toggle` is called

### ISSUE THREAD

**Issue by Ambrevar** [holomorph/transmission#10]
Emacs: 25.2

Whenever I call `transmission-turtle-toggle` I get a "Enable turtle mode? Yes No" graphical dialog box. Which I don't like much...
Sometimes it does not happen the first time. But it does every subsequent calls.

I've had a look at the code but it left me puzzled with why it does this.
Other commands using the `y-or-no-p` such as `transmission-verify` do not display that behaviour.

**Comment by holomorph** [comment]
I can reproduce.  If you _never_ want dialog boxes, you can alter the variable `use-dialog-box`.  At first sight, `transmission-turtle-toggle` appears to be the only place where `y-or-n-p` is in an asynchronous callback, so perhaps that has something to do with it.

**Comment by holomorph** [comment]
In any case, I think it makes sense to simply remove the prompt and have the ultimate message tell whether it was enabled or disabled.  Alternatively, do like `transmission-turtle-set-speeds` and have the first request be synchronous and the `y-or-n-p` prompts in the interactive spec where they belong :)

**Comment by Ambrevar** [comment]
:+1:

**Comment by holomorph** [comment]
fixed in a48571d. thanks!
