### ISSUE TITLE
Feature Suggestion: demote/promote torrent order

### ISSUE THREAD

**Issue by spiderbit** [holomorph/transmission#11]
Transmission has a order in which it downloads files, so if you have 10 torrents added and you have in your setup that it will download 4 files at the same time and you add a new torrent, but want it to be downloaded before the other files, currently the only way would be to pause the 10 previous torrents or at least 7 of em wait till the file you wanted is downloaded and then manually resume all other files again.

At least I did not find a promote / demote shortcut / function in this transmission-mode.

**Comment by holomorph** [comment]
Thanks, there are now queue manipulation commands in 1a12fa5

**Comment by spiderbit** [comment]
gosh that is the first feature request without me writing the code that got accepted. You are such a nice author. I am even myself to lazy to fulfill them on my projects.

Really great work thanks again!

**Comment by holomorph** [comment]
Thanks and you're welcome! \o/
