### ISSUE TITLE
Transmission-add fails when using selectrum and a magnet link

### ISSUE THREAD

**Issue by mtreca** [holomorph/transmission#17]
When using the [selectrum](https://github.com/raxod502/selectrum) completion framework, adding a torrent using `transmission-add` while having a magnet link in the kill ring results in:

```
Wrong type argument: stringp, ("magnet:?xt=urn:btih:c12fe1c06bba254a9dc9f519b335aa7c1367a88a")
```

(the magnet link is taken from [Wikipedia](https://en.wikipedia.org/wiki/Magnet_URI_scheme), but the same behavior is observed with multiple links).

Directly evaluating `(transmission-add "magnet:?xt=urn:btih:c12fe1c06bba254a9dc9f519b335aa7c1367a88a")` does function, however.

**Comment by VojtechStep** [comment]
Should be resolved in upstream if [the PR](https://github.com/raxod502/selectrum/pull/401) is merged.

Note that to select the link in clipboard, you need to delete the prefilled text and then select the default. [An issue](https://github.com/raxod502/selectrum/issues/400) exists for this as well.

**Comment by VojtechStep** [comment]
Please try again with the master branch of selectrum, it should be fixed now.

**Comment by mtreca** [comment]
Tried from latest master, everything is working well!
