### ISSUE TITLE
*transmission* buffer not "live" updating

### ISSUE THREAD

**Issue by grolongo** [holomorph/transmission#20]
Hello,

When I'm adding a torrent or magnet link with `transmission-add`, the torrent doesn't show up until I kill the `*transmission*` buffer and reopen it. It also doesn't seem to refresh anything "live", I have to kill and do `M-x transmission` each time.

Same thing happens when I use `transmission-remote -a foo.torrent` in the terminal and then checking it in Emacs. It shows up but just not updates in real-time.

It's the first time I'm using this package, not sure if that's a normal behavior.

I'm using Emacs 27.2 on macOS.

**Comment by VojtechStep** [comment]
Hi, yes, this is expected behavior - by default, none of the transmission buffers autoupdate.

You can either refresh the buffer manually by calling `revert-buffer` (I for example have this bound everywhere on `SPC gr`), or you can add the mode to the `transmission-refresh-modes` list variable, which makes it refresh every `transmission-refresh-interval` (by default 2 seconds).

**Comment by grolongo** [comment]
Hey thanks a lot, looks like `revert-buffer` is already binded with `g` by default in `transmission-mode`.

I checked `transmission-refresh-modes` like you mentioned and enabled everything that was in the list:

```elisp
(setq transmission-refresh-modes
      '(transmission-mode
        transmission-files-mode
        transmission-info-mode
        transmission-peers-mode))
```

Not sure what all this does and that might be overkill, but it does refresh the transmission buffer automatically.

Now I wonder why this is not enabled by default? Looks like I'm the only one who raised an issue about this but I think it would be better to have it enabled directly as it provides better UX out of the box.

**Comment by VojtechStep** [comment]
I'm not sure why it's not the default either, guess I'm just used to using `revert-buffer` to refresh in other buffers too.
I guess a PR to change the default behavior could be accepted, as it could always be turned off if necessary.
