### ISSUE TITLE
Mark/operate several torrents at once

### ISSUE THREAD

**Issue by smaximov** [holomorph/transmission#3]
I know that it's possible to select successive torrents using regions, but it's often useful to mark arbitrary torrents to apply an action to them at once in the fashion of `dired-mode` or `package-menu-mode` (the latter shares its parent mode with `transmission-mode`, so it can be used as a reference).

**Comment by holomorph** [comment]
Sorry for the long wait--this is now implemented in the new-interactive branch.  I'll incubate it there for a while in the interest of finding bugs/improving things, then merge to master

**Comment by holomorph** [comment]
Merged in d015272! whew
