### ISSUE TITLE
transmission buffer doesn't update.

### ISSUE THREAD

**Issue by JAremko** [holomorph/transmission#6]
I'm trying to integrate transmission.el into [Spacemacs](https://github.com/syl20bnr/spacemacs)  but for some reason transmission buffer doesn't update. Even when I close/open it.
 It will show a new state only if I kill the buffer and recreate it but it will not automatically update.

Emacs 24 on Debian with `transmission-daemon` package. I run it with `rpc-authentication-required": false`

**Comment by JAremko** [comment]
When I call `transmission-draw` manually it works.   It just doesn't auto refresh for some reason :confused:

**Comment by holomorph** [comment]
did you read the readme

**Comment by JAremko** [comment]
As allways  :smile: 

<s>So I need to install it?  I fired it up and it seems to all be good except auto update.</s>

Aha. So the refresh is disabled for all modes by default(no word in the readme about it)  This is strange actually. It should at least refresh when I open those buffers :confused:

**Comment by JAremko** [comment]
Ok thanks for the hint. And the package :wink:
